### PR TITLE
Fix for "GeographyDirectory" file path parameter for IPlocation

### PR DESCRIPTION
**Pull request by kanduibm**
Added a fix to convert "geographyDirectory" parameter value to absolute path when necessary. This parameter now can take both relative and absolute path.

### CODE REVIEW

**Comment by ejpring** [comment]
The 'geographyDirectory' parameter definitely needs to handle both relative and absolute pathnames, but I'm not sure this is quite the right way to do it:

```
  if(filepath.is_relative()) {
    filepath = streams_boost::filesystem::absolute(filepath, getPE().getDataDirectory());
  }
```

The 'data' directory is optional in Streams release 4, isn't it? If so, what does getDataDirectory() return if the application was compiled without the '--dataDirectory' parameter, and the directory does not exist?

Relative pathnames should certainly be resolved into absolute pathnames at runtime, but I think they should be relative to the current working directory. That could be the 'data' directory, the Eclipse project directory, somewhere in /tmp, or someplace else entirely. I think this code will accomplish that:

```
  if(filepath.is_relative()) {
    filepath = streams_boost::filesystem::absolute(filepath);
  }
```

but you should verify that ...

-- Ed

**Comment by cancilla** [comment]
I think the question here is, what are the geography files? Are they data files that the user may want/need to update? Or are they static files (similar to a configuration file) that will never change during the lifetime of the operator? 

If they are data files, then making them relative to the data directory by default is standard practice. If they are configuration files, then they should be relative to the toolkit directory. In the later case, the files should be placed in the 'etc' folder so they get added to the application bundle.

**Comment by ejpring** [comment]
Customers must download geography data from Maxmind Inc. (see http://dev.maxmind.com/geoip/geoip2/geolite2/ for the free version, which is updated monthly, and https://www.maxmind.com/en/geoip2-city/ for the priced version, which is updated more frequently). 

I'm not sure I understand your comment about application bundles and the 'etc' directory. Geography data should be included in application bundles, whatever directory its in, since its required by the operator at initialization.

**Comment by cancilla** [comment]
If the geography data is included in the application bundle, that implies that the data is static and will never change. In order to update the geography data, the user would need to download that data into their application project, recompile the application in order to generate a new bundle and then relaunch the application. Or to put it another way, a user would need to take their application offline in order to update the geography data stored in the application bundle. 

By putting the geography data in the 'data' directory, this makes it possible for the user to update that data without interrupting their application (assuming of course that the operator is capable of supporting dynamically updating this data). The caveat here is that you need to ensure that the application is compiled with a data directory.

My point about the 'etc' directory is, if it's decided that the geography data should be included in the application bundle, then this data should be placed in the 'etc' directory, which is included in the application bundle by default.

**Comment by ejpring** [comment]
OK, now I understand the distinction between the 'data' and 'etc' directories. That does create an ambiguity for geography data, though. For most customers, this sort of data is static -- the developer will download the free data from Maxmind once and never change it. But I can imagine applications that might need the latest updates to the Maxmind data, and customers that would be willing to pay for it.

So I think we should recommend that geography data be placed in the 'data' directory (or some other directory outside the Eclipse workspace) and referenced with an absolute pathname. That's what all of the sample applications in the toolkit do. 

I think we should also have an example of an 'info.xml' file that bundles the data directory into the application bundle for situations that need that, like cloud deployments.

**Comment by cancilla** [comment]
We don't necessarily need to provide an example of how to bundle the data directory. The issue here is which directory are relative paths relative to. I agree that making the data directory the default relative path makes sense for these files.

For cloud deployments or cases where the user wants to ensure the geography data is included in the application bundle, they can still put the files in the 'etc' directory (for example) and refer to it using the 'getThisToolkitDir()' function, which returns the absolute path to the root of the application directory within the bundle. 

For example, if the geography data was stored in the 'etc' directory, a user can add that path to their application using the following code snippet:

```
  param
    geographyDirectory : getThisToolkitDir() + "/etc/" ;
```

**Comment by kanduibm** [comment]
Hi Edward 
I tested the following code change you suggested but it did work . If we use a relative path for the geography directory such as "../dir1/dir2/<geodata-file.csv>, the operator will not be able to find it and an exception will be thrown. 

  if(filepath.is_relative()) {
    filepath = streams_boost::filesystem::absolute(filepath);
  }

 filepath = streams_boost::filesystem::absolute(filepath, getPE().getDataDirectory()); This code change works for both absolute and relative path  for example : (../../<geodata.csv> or /dir/dir/<geodata.csv>) 

Thanks

**Comment by ejpring** [comment]
OK -- if that works, then let's go with it!

**Comment by cancilla** [comment]
Sounds like we are all in agreement on this. If there are no concerns, I will merge in this pull request. 

@kanduibm Please open an issue for this problem and reply back with the issue #. I will merge this request once I get the issue #.

**Comment by cancilla** [comment]
Fixes issue #37

**Pull request merged**
